DROP TABLE `cmsplugin_attachmentplugin`;
DROP TABLE `cmsplugin_fundingopportunityplugin`;
DROP TABLE `cmsplugin_googlemapplugin`;
DROP TABLE `cmsplugin_investmentformplugin`;
DROP TABLE `cmsplugin_investmentsplugin`;
DROP TABLE `cmsplugin_notificationplugin`;
DROP TABLE `cmsplugin_organizationformplugin`;
DROP TABLE `cmsplugin_organizationplugin`;
DROP TABLE `cmsplugin_projectformplugin`;
DROP TABLE `cmsplugin_projectsplugin`;
DROP TABLE `cmsplugin_searchprojectplugin`;
DROP TABLE `cmsplugin_userdetailplugin`;
DROP TABLE `cmsplugin_userformplugin`;

DELETE FROM cms_cmsplugin WHERE plugin_type="CMSCarouselProjectPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSFormInvestmentPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSFormProjectPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSFundingOpportunitiesPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSGoogleMapPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSInvestmentsPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSLatestFundingOpportunityPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSLatestOrganizationsPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSLatestProjectsPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSOrganizationPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSPFormOrganizationPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSProjectsPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSSearchProjectPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSUserFormPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSGlobalSearchListPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSMapLinkPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSSamplingPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSNotificationPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSDetailUserPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSUserFormPlugin";
DELETE FROM cms_cmsplugin WHERE plugin_type="CMSSponsorsPlugin";

ALTER TABLE `cmsplugin_listimageplugin` DROP PRIMARY KEY;
ALTER TABLE `cmsplugin_listimageplugin` DROP FOREIGN KEY `cmsplugin_ptr_id`;
ALTER TABLE `cmsplugin_listimageplugin` DROP FOREIGN KEY `cmsplugin_ptr_id_refs_id_818606cc`;
